### ISSUE TITLE
Redirection failed after login

### ISSUE THREAD

**Issue by P100sch** [codekidX/code_riddler#1]
After allowing access to your GitHub account information, the redirection leads back to the login.

**Comment by codekidX** [comment]
@P100sch Hello, are you able to see the `Solve` button instead of Login after Github Authentication?

**Comment by hshah2801** [comment]
> @P100sch Hello, are you able to see the `Solve` button instead of Login after Github Authentication?

NO

**Comment by P100sch** [comment]
> 
> 
> @P100sch Hello, are you able to see the `Solve` button instead of Login after Github Authentication?

No, just the login button.

**Comment by codekidX** [comment]
Thanks for reporting @P100sch  @hshah2801 . It was a bug with authentication middleware. I'll post code ASAP but `Solve` button should be visible now. Do let me know if it works for you guys.

**Comment by P100sch** [comment]
Yes it works. Thank you.
